CREATE TABLE jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id VARCHAR(100),
    job_title VARCHAR(255) NOT NULL,
    description TEXT,
    experience_min INTEGER,
    experience_max INTEGER,
    compensation_min INTEGER,
    compensation_max INTEGER,
    currency VARCHAR(10),
    visa_required BOOLEAN,
    work_mode VARCHAR(50),
    work_type VARCHAR(50),
    preference VARCHAR(255),
    no_of_rounds INTEGER,
    interview_mode VARCHAR(50),
    bond_period VARCHAR(100),
    shift_timings VARCHAR(100),
    overtime_applicable BOOLEAN,
    bonuses TEXT,
    pay_schedule VARCHAR(50),
    posted_at DATETIME,
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    application_url TEXT,
    education_required VARCHAR(255),
    languages_required TEXT,
    contract_duration VARCHAR(100),
    remote_location_restriction VARCHAR(255),
    source VARCHAR(100)
);
