// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/jobs": {
            "get": {
                "description": "Returns paginated list of jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Get all jobs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new job entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Create a new job",
                "parameters": [
                    {
                        "description": "Job object",
                        "name": "job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.JobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    }
                }
            }
        },
        "/jobs/batch": {
            "delete": {
                "description": "Deletes multiple jobs by IDs or JobIDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Batch delete jobs",
                "parameters": [
                    {
                        "description": "Batch delete request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.BatchDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    }
                }
            }
        },
        "/jobs/search": {
            "get": {
                "description": "Searches jobs with filters like query, work mode, skills, salary, etc.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Search jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Currency code",
                        "name": "currency",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated work modes",
                        "name": "work_mode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated work types",
                        "name": "work_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated skills",
                        "name": "skills",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated sources",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum salary",
                        "name": "min_salary",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum salary",
                        "name": "max_salary",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter active jobs",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    }
                }
            }
        },
        "/jobs/stats": {
            "get": {
                "description": "Returns statistics about jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Get job statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{id}": {
            "get": {
                "description": "Returns a job by its internal ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Get job by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a job by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Delete a job",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/deactivate": {
            "patch": {
                "description": "Marks a job as inactive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Deactivate a job",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "constant.Currency": {
            "type": "string",
            "enum": [
                "USD",
                "EUR",
                "GBP",
                "INR"
            ],
            "x-enum-varnames": [
                "CurrencyUSD",
                "CurrencyEUR",
                "CurrencyGBP",
                "CurrencyINR"
            ]
        },
        "constant.ExperienceLevel": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "ExperienceLevelEntry",
                "ExperienceLevelMid",
                "ExperienceLevelSenior",
                "ExperienceLevelLead",
                "ExperienceLevelExecutive"
            ]
        },
        "constant.JobType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "JobTypeFullTime",
                "JobTypePartTime",
                "JobTypeContract",
                "JobTypeInternship",
                "JobTypeTemporary"
            ]
        },
        "constant.WorkMode": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "WorkModeRemote",
                "WorkModeOnsite",
                "WorkModeHybrid"
            ]
        },
        "dtos.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string",
                    "example": "Something went wrong"
                },
                "message": {
                    "type": "string",
                    "example": "Operation successful"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dtos.BatchDeleteRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dtos.JobRequest": {
            "type": "object",
            "properties": {
                "apply_url": {
                    "type": "string",
                    "example": "https://techcorp.com/careers/12345"
                },
                "categories": {
                    "type": "string",
                    "example": "Engineering, IT"
                },
                "city": {
                    "type": "string",
                    "example": "San Francisco"
                },
                "company": {
                    "type": "string",
                    "example": "Tech Corp"
                },
                "country": {
                    "type": "string",
                    "example": "USA"
                },
                "department": {
                    "type": "string",
                    "example": "Engineering"
                },
                "description": {
                    "type": "string",
                    "example": "Job description here"
                },
                "education_level": {
                    "type": "string",
                    "example": "Bachelor's"
                },
                "experience_level": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/constant.ExperienceLevel"
                        }
                    ],
                    "example": 1
                },
                "external_job_id": {
                    "type": "string",
                    "example": "ext-12345"
                },
                "industry": {
                    "type": "string",
                    "example": "Information Technology"
                },
                "is_remote": {
                    "type": "boolean",
                    "example": false
                },
                "job_type": {
                    "description": "\"full-time\", \"part-time\", \"contract\", \"remote\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/constant.JobType"
                        }
                    ],
                    "example": 1
                },
                "posted_at": {
                    "type": "string",
                    "example": "2023-10-01T12:00:00Z"
                },
                "salary_currency": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/constant.Currency"
                        }
                    ],
                    "example": "USD"
                },
                "salary_max": {
                    "type": "integer",
                    "example": 120000
                },
                "salary_min": {
                    "type": "integer",
                    "example": 60000
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Go",
                        " Docker",
                        " Kubernetes"
                    ]
                },
                "slug": {
                    "type": "string",
                    "example": "software-engineer-12345"
                },
                "source": {
                    "type": "string",
                    "example": "LinkedIn"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "urgent",
                        "remote"
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "Software Engineer"
                },
                "visa_sponsorship": {
                    "type": "boolean",
                    "example": false
                },
                "work_mode": {
                    "description": "\"onsite\", \"remote\", \"hybrid\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/constant.WorkMode"
                        }
                    ],
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
