definitions:
  constant.Currency:
    enum:
    - USD
    - EUR
    - GBP
    - INR
    type: string
    x-enum-varnames:
    - CurrencyUSD
    - CurrencyEUR
    - CurrencyGBP
    - CurrencyINR
  constant.ExperienceLevel:
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    type: integer
    x-enum-varnames:
    - ExperienceLevelEntry
    - ExperienceLevelMid
    - ExperienceLevelSenior
    - ExperienceLevelLead
    - ExperienceLevelExecutive
  constant.JobType:
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    type: integer
    x-enum-varnames:
    - JobTypeFullTime
    - JobTypePartTime
    - JobTypeContract
    - JobTypeInternship
    - JobTypeTemporary
  constant.WorkMode:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - WorkModeRemote
    - WorkModeOnsite
    - WorkModeHybrid
  dtos.APIResponse:
    properties:
      data: {}
      error:
        example: Something went wrong
        type: string
      message:
        example: Operation successful
        type: string
      success:
        example: true
        type: boolean
    type: object
  dtos.BatchDeleteRequest:
    properties:
      ids:
        items:
          type: integer
        type: array
    type: object
  dtos.JobRequest:
    properties:
      apply_url:
        example: https://techcorp.com/careers/12345
        type: string
      categories:
        example: Engineering, IT
        type: string
      city:
        example: San Francisco
        type: string
      company:
        example: Tech Corp
        type: string
      country:
        example: USA
        type: string
      department:
        example: Engineering
        type: string
      description:
        example: Job description here
        type: string
      education_level:
        example: Bachelor's
        type: string
      experience_level:
        allOf:
        - $ref: '#/definitions/constant.ExperienceLevel'
        example: 1
      external_job_id:
        example: ext-12345
        type: string
      industry:
        example: Information Technology
        type: string
      is_remote:
        example: false
        type: boolean
      job_type:
        allOf:
        - $ref: '#/definitions/constant.JobType'
        description: '"full-time", "part-time", "contract", "remote"'
        example: 1
      posted_at:
        example: "2023-10-01T12:00:00Z"
        type: string
      salary_currency:
        allOf:
        - $ref: '#/definitions/constant.Currency'
        example: USD
      salary_max:
        example: 120000
        type: integer
      salary_min:
        example: 60000
        type: integer
      skills:
        example:
        - Go
        - ' Docker'
        - ' Kubernetes'
        items:
          type: string
        type: array
      slug:
        example: software-engineer-12345
        type: string
      source:
        example: LinkedIn
        type: string
      tags:
        example:
        - urgent
        - remote
        items:
          type: string
        type: array
      title:
        example: Software Engineer
        type: string
      visa_sponsorship:
        example: false
        type: boolean
      work_mode:
        allOf:
        - $ref: '#/definitions/constant.WorkMode'
        description: '"onsite", "remote", "hybrid"'
        example: 1
    type: object
info:
  contact: {}
paths:
  /jobs:
    get:
      description: Returns paginated list of jobs
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Get all jobs
      tags:
      - Jobs
    post:
      consumes:
      - application/json
      description: Creates a new job entry
      parameters:
      - description: Job object
        in: body
        name: job
        required: true
        schema:
          $ref: '#/definitions/dtos.JobRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Create a new job
      tags:
      - Jobs
  /jobs/{id}:
    delete:
      description: Deletes a job by ID
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Delete a job
      tags:
      - Jobs
    get:
      description: Returns a job by its internal ID
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Get job by ID
      tags:
      - Jobs
  /jobs/{id}/deactivate:
    patch:
      description: Marks a job as inactive
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Deactivate a job
      tags:
      - Jobs
  /jobs/batch:
    delete:
      consumes:
      - application/json
      description: Deletes multiple jobs by IDs or JobIDs
      parameters:
      - description: Batch delete request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.BatchDeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Batch delete jobs
      tags:
      - Jobs
  /jobs/search:
    get:
      description: Searches jobs with filters like query, work mode, skills, salary,
        etc.
      parameters:
      - description: Search keyword
        in: query
        name: query
        type: string
      - description: Currency code
        in: query
        name: currency
        type: string
      - description: Comma-separated work modes
        in: query
        name: work_mode
        type: string
      - description: Comma-separated work types
        in: query
        name: work_type
        type: string
      - description: Comma-separated skills
        in: query
        name: skills
        type: string
      - description: Comma-separated sources
        in: query
        name: source
        type: string
      - description: Minimum salary
        in: query
        name: min_salary
        type: integer
      - description: Maximum salary
        in: query
        name: max_salary
        type: integer
      - description: Filter active jobs
        in: query
        name: is_active
        type: boolean
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Search jobs
      tags:
      - Jobs
  /jobs/stats:
    get:
      description: Returns statistics about jobs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Get job statistics
      tags:
      - Jobs
swagger: "2.0"
